mss-boot-io/mss-boot

- testdata/test.yml
- virtual/model/model.go
- virtual/model/model_test.go
> :bug: fix: search type

- go.mod
- go.sum
- pkg/config/gormdb/open.go
- pkg/migration/models/migrate.go
> :sparkles: feat: support dm db

- pkg/migration/make.go
> :bug: fix: migrate table name

- pkg/config/gormdb/open.go
- pkg/search/gorms/query.go
> :sparkles: support dm search

- pkg/search/gorms/query.go
> :bug: fix: condition

- pkg/config/config.go
- pkg/config/storage.go
- pkg/config/storage_test.go
> Compatible with minion storage

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/gormdb/gorm.go
- pkg/config/gormdb/open.go
- pkg/config/source/gorm/gorm.go
- pkg/config/source/mgdb/mgdb.go
- pkg/config/source/options.go
- pkg/config/source/type.go
> :sparkles: load config from database by gorm enabled

- pkg/migration/make.go
> :bug: fix: migrate version

- pkg/migration/make.go
- pkg/migration/models/migrate.go
> 🐛 : fix migrate error

- core/server/listener/server.go
> :sparkles: add http server start print

- README.Zh-cn.md
- README.md
> :memo: update readme

- .github/workflows/mirror-template.yml
- .github/workflows/mirror.yml
> add mirror workflow template

- pkg/response/actions/base.go
- pkg/response/actions/control_gorm.go
- pkg/response/actions/delete_gorm.go
- pkg/response/actions/get_gorm.go
- pkg/response/actions/search_gorm.go
- pkg/response/controller/options.go
- pkg/response/controller/simple.go
- pkg/utils.go
> :sparkles: support multiple tenant

- pkg/response/action.go
- pkg/response/actions/base.go
- pkg/response/actions/control_gorm.go
- pkg/response/actions/control_mgm.go
- pkg/response/actions/delete_gorm.go
- pkg/response/actions/delete_mgm.go
- pkg/response/actions/get_gorm.go
- pkg/response/actions/get_mgm.go
- pkg/response/actions/search_gorm.go
- pkg/response/actions/search_mgm.go
- pkg/response/actions/type.go
- pkg/response/controller/options.go
- pkg/response/controller/simple.go
- pkg/utils.go
- virtual/action/base.go
- virtual/action/create.go
- virtual/action/delete.go
- virtual/action/get.go
- virtual/action/search.go
- virtual/action/update.go
- virtual/model/model.go
> :sparkles: tenant enabled

- pkg/config/grpc.go
- pkg/utils.go
> :sparkles: add data scope

- pkg/response/actions/gorm/control.go
- pkg/response/actions/gorm/search.go
- pkg/response/api.go
- pkg/utils.go
> :sparkles: feat: data scope enabled

- go.mod
- go.sum
- pkg/config/config.go
- pkg/config/source/entity.go
- pkg/config/source/fs/fs.go
- pkg/config/source/gorm/gorm.go
- pkg/config/source/local/local.go
- pkg/config/source/mgdb/mgdb.go
- pkg/config/source/options.go
- pkg/config/source/s3/s3.go
- pkg/config/type.go
> :sparkles: support local config file watch

- pkg/response/actions/gorm/control.go
- pkg/response/actions/gorm/delete.go
- pkg/response/actions/gorm/get.go
- pkg/response/actions/gorm/options.go
- pkg/response/actions/gorm/search.go
- pkg/response/controller/options.go
- pkg/response/controller/simple.go
> :sparkles: feat: add actions hook

- pkg/config/config.go
- pkg/config/gormdb/gorm.go
- pkg/config/source/entity.go
- pkg/config/source/options.go
- pkg/utils.go
> :sparkles: feat: support aws secretmanager and k8s secret

- core/logger/writer/loki.go
- core/server/server.go
- pkg/response/actions/gorm/base.go
- pkg/response/actions/gorm/control.go
- pkg/response/actions/gorm/delete.go
- pkg/response/actions/gorm/get.go
- pkg/response/actions/gorm/search.go
> :sparkles: feat: support query cache

- pkg/config/gormdb/config.go
> :bug: fix: db pool limit

- pkg/response/actions/gorm/options.go
- pkg/response/actions/k8s/options.go
> :bug: fix: tenant auth scope

- .github/dependabot.yml
- .github/workflows/release.yml
- pkg/config/grpc.go
> :bug: fix: dependabot package

- pkg/config/grpc.go
> :sparkles: feat: support grpc custom options

- pkg/security/security.go
> :sparkles: feat: support person access token

- pkg/security/security.go
> :bug: fix: person access token index error

- pkg/search/gorms/query.go
> :sparkles: feat: search support between

- core/server/default.go
- go.mod
> :bug: rollback go version

- pkg/response/actions/pagination.go
https://github.com/mss-boot-io/mss-boot-admin/issues/157
> :bug: fix: page for antd pro

- pkg/response/actions/gorm/search.go
> :bug: fix: search current page delete

- virtual/action/type.go
> :bug: fix: page for virtual action

- pkg/response/actions/mgm/control.go
- pkg/response/actions/mgm/delete.go
- pkg/response/actions/mgm/get.go
- pkg/response/actions/mgm/search.go
> :bug: fix: mongo action

- pkg/config/gormdb/gorm.go
- pkg/search/gorms/query.go
> :bug: fix: update SQL query formatting and restore package import
